### ISSUE TITLE
how to fake DNS with dns country  of china? Can you give me a website to check fake Dns  success or not?

### ISSUE THREAD

**Issue by ghost** [danielperna84/myip-fakedns#1]

**Comment by danielperna84** [comment]
That's not what this tool is about. This tool returns the same IP (your IP) on every DNS request your device sends. With this enabled you won't be able to browse the internet at all. It breaks the internet for your device.

**Comment by henryhoang92** [comment]
Yes. I want keep my Ip but fake DNS in  my list .
is It fake  IP addresses - WebRTC detection at site https://ipleak.net/?

**Comment by danielperna84** [comment]
I don't think I understand your question.
Yes, this tool would do the same as ipleak.net, but not via browser but by using a DNS query, which is much faster. You would need a server in the internet where this would be running, and then you could do a DNS query from wherever you are for any site, and you would always get your public IP.

**Comment by ghost** [comment]
Yes. I want fake DNS address in list ("210.245.24.83", "210.245.24.84"). How can i do it?.   maybe I cannot know how to use your lib... 
Thanks

**Comment by danielperna84** [comment]
You have to install Python and just execute the script. Then you configure your operating system to use one of your local interface addresses as the DNS server. That could be 127.0.0.1. Once that is done, every hostname will resolve to 127.0.0.1 and you won't be able to access any website via hostname anymore.
This does not forward DNS requests. So you can not somehow integrate other DNS servers. This is just a little helper to find out what your client IP address is, so it doesn't do anything with other DNS servers.

**Comment by henryhoang92** [comment]
Do you know how to fake DNS  and WEB RTC  at ipleadk.net ?

**Comment by danielperna84** [comment]
No, I do not know that. Sorry. Although the information on that site says that this problem only applies to Windows. So you could simply have a Linux VM for browsing I assume.

**Comment by danielperna84** [comment]
If it's worth the effort: you could also run your own DNS server on that Linux VM. On Debian based systems (which also includes Ubuntu) you could install one with the command `sudo apt-get install bind9`. You then would need to configure it to forward requests it can't answer itself to another DNS like the ones from https://www.opendns.com/.

**Comment by ghost** [comment]
I'm trying to run your script on PC and I'm using a android emulator go to page whoer.net
here log:
whoer.net  -> 127.0.0.1
whoer.net  -> 127.0.0.1
whoer.net  -> 127.0.0.1

But I cannot access whoer.net page or any website. Do you know how to make your lib can be access via other dns in android emulator . (may be, can you use other dns ex: 
DNS IP Address: 93.189.88.51
DNS Name: ns-vps-01.icode.es )

Thanks

**Comment by danielperna84** [comment]
You can't access that site exactly because, like I've said before, this is not the tool you are looking for. Instead of giving you the correct IP for the host you want to access, it returns your own local address. That's what this is made for. It is only useful for network analysis.
You can't make my script do what you want it to do because it is not designed to do that.

You probably need a real DNS server where you can manually specify forward DNS servers. Just like I've mentioned in my previous answer.
